Repository astarte-platform/astarte-device-sdk-elixir, pull requests merged in 2020-08, with the labels that each got.

#16 Follow HTTP redirects
  .tool-versions
  lib/astarte_api.ex
  lib/astarte_device.ex
  lib/astarte_device/impl.ex
  mix.lock
Labels: blocking, main feature

#18 Pass customize_hostname_check to SSL options
  CHANGELOG.md
  lib/astarte_device/tortoise_connection.ex
Labels: bug, user experience

#17 Prepare v0.11.2 release
  .tool-versions
  CHANGELOG.md
  mix.exs
  mix.lock
Labels: chore
